language: r
r:
  - release
  - devel
sudo: false
cache: packages
addons:
   apt:
    packages:
      - librdf0-dev
services: docker
before_install:
  - docker run --name rt -p 8888:80 netsandbox/request-tracker