
sudo: required
language: r
r:
  - release
  - devel
cache: packages
addons:
   apt:
    packages:
      - librdf0-dev
services: docker
before_install:
  - docker run -d --name rt -p 8080:80 netsandbox/request-tracker
