name: CI

on: [push]

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: amoeba/rcmdcheck-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
